### ISSUE TITLE
Do you have the training code?

### ISSUE THREAD

**Issue by ThomasKKL** [benjaminjellis/RepNetPyTorch#1]
Do you have the training code? can you send me by the email? my email  is 1165691591@qq.com, thanks very much!

**Comment by benjaminjellis** [comment]
Hi, 

I don't have a training script, and at present, I don't think I'm going to be writing one. 

The intention at present is to convert the tf weights supplied by the authors but I don't have a timeline for when this will be done. 

If you chose to write a training script please feel free to create a pr!

Thanks :)
