### ISSUE TITLE
How can I expand frame number?

### ISSUE THREAD

**Issue by seawavve** [benjaminjellis/RepNetPyTorch#3]
I want to see TSM and run this code over 64 frame number.
When I try it, tensor uncompatiable error occurs.
How can I change the frame number? Can you help me?

**Comment by benjaminjellis** [comment]
Hi, 

A few things: 

- what do you want to change the number of frames to? (I'm assuming you're referring to the instance variable ```self.num_frames```) 
- can you provide a stack trace for the error you're getting? I've never come across a torch error like "tensor uncompatiable" so not sure what could be causing this 

Thanks :)

**Comment by seawavve** [comment]
yes, I want to change `self.num_frames`. When I set num_frames to 500 and run this model, The error occurs like 

ckpt-88.index       100%[===================>]  12.86K  --.-KB/s    in 0s      

2021-10-12 01:14:24 (99.3 MB/s) - ‘/tmp/repnet_ckpt/ckpt-88.index’ saved [13172/13172]

/usr/local/lib/python3.7/dist-packages/keras/backend.py:401: UserWarning: `tf.keras.backend.set_learning_phase` is deprecated and will be removed after 2020-10-11. To update it, simply pass a True/False value to the `training` argument of the `__call__` method of your layer or model.
  warnings.warn('`tf.keras.backend.set_learning_phase` is deprecated and '
Loading from:  /tmp/repnet_ckpt/ckpt-88
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-301bdff45697> in <module>()
      6 get_ipython().system('wget -nc -P $PATH_TO_CKPT https://storage.googleapis.com/repnet_ckpt/ckpt-88.index')
      7 
----> 8 model = get_repnet_model(PATH_TO_CKPT)

12 frames
/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/tensor_shape.py in assert_is_compatible_with(self, other)
   1159     """
   1160     if not self.is_compatible_with(other):
-> 1161       raise ValueError("Shapes %s and %s are incompatible" % (self, other))
   1162 
   1163   def most_specific_compatible_shape(self, other):

ValueError: Shapes (1, 500, 1) and (1, 64, 1) are incompatible

**Comment by seawavve** [comment]
I knew that I cannot run in larger frame number because the checkout model file is fixed with 64 frame. Then, I want to see the TSM of the enlarged frame numpy array at least. Can I?

**Comment by benjaminjellis** [comment]
The stack trace is a tensorflow error, this is a repo for an unofficial pytorch port. I can see that what you're doing is trying to load the author provided checkpoint into a model that's instantiated with different parameters and thus the shape of the instantiated model weights aren't the same as the weights in the checkpoint file thus why you're getting the error. 

You can get the TSM for this pytorch port, but you'd need to add a hook ([see here](https://blog.paperspace.com/pytorch-hooks-gradient-clipping-debugging/)) to the TSM tensor. 

Hopefully this answers your question!

**Comment by seawavve** [comment]
Yes I got that I want. Thank  you :)
