### ISSUE TITLE
sampling strategy for training and testing

### ISSUE THREAD

**Issue by bridgeqiqi** [benjaminjellis/RepNetPyTorch#5]
Hi, Thank you for your great work of reproducing the model in a pytorch version. I have a small concern of the data preprocessing. I am not sure whether the frame sampling strategies are the same for both training and testing stage. This paper claim that they sample consecutive non-overlapping 64 frames during the inference and testing time but I don't know how to sample the 64 video frames for training. Do you have any advice for it?

**Comment by benjaminjellis** [comment]
Hi @bridgeqiqi, 

I don't have any advice for sampling frames as I've not trained repnet or tried to reproduce the original authors results. Question about the paper's methodology are best directed to the author who are listed at the top of the page [here](https://sites.google.com/view/repnet).

Hopefully that answers your question, if not please feel free to reopen. 

Thank,
Benjamin
