### ISSUE TITLE
training

### ISSUE THREAD

**Issue by guoxigan** [benjaminjellis/RepNetPyTorch#6]
Thanks for your good job!  would u like to share  the trainning code with us?

**Comment by benjaminjellis** [comment]
Hi, 

Thanks for opening an issue. At present I don't have any training code and I haven't attempted to train this model. 

My preferred approach would be to port the tf weights but again I haven't attempted to do that. 

I'm going to close to issue for now but please feel free to reopen if you have any further questions.

Thanks!
